/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AgentList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentList{}

// AgentList A list of agent entities.
type AgentList struct {
	Items         []Agent `json:"items,omitempty"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
	PageSize      *int32  `json:"pageSize,omitempty"`
	Size          *int32  `json:"size,omitempty"`
}

// NewAgentList instantiates a new AgentList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentList() *AgentList {
	this := AgentList{}
	return &this
}

// NewAgentListWithDefaults instantiates a new AgentList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentListWithDefaults() *AgentList {
	this := AgentList{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *AgentList) GetItems() []Agent {
	if o == nil || IsNil(o.Items) {
		var ret []Agent
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentList) GetItemsOk() ([]Agent, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *AgentList) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Agent and assigns it to the Items field.
func (o *AgentList) SetItems(v []Agent) {
	o.Items = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *AgentList) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentList) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *AgentList) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *AgentList) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *AgentList) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentList) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *AgentList) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *AgentList) SetPageSize(v int32) {
	o.PageSize = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *AgentList) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentList) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *AgentList) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *AgentList) SetSize(v int32) {
	o.Size = &v
}

func (o AgentList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	return toSerialize, nil
}

type NullableAgentList struct {
	value *AgentList
	isSet bool
}

func (v NullableAgentList) Get() *AgentList {
	return v.value
}

func (v *NullableAgentList) Set(val *AgentList) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentList) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentList(val *AgentList) *NullableAgentList {
	return &NullableAgentList{value: val, isSet: true}
}

func (v NullableAgentList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
