// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Catalog REST API
 *
 * REST API for Kubeflow Hub Catalog
 *
 * API version: v1alpha1
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"

	model "github.com/kubeflow/hub/catalog/pkg/openapi"
)

// AgentCatalogServiceAPIController binds http requests to an api service and writes the service results to the http response
type AgentCatalogServiceAPIController struct {
	service      AgentCatalogServiceAPIServicer
	errorHandler ErrorHandler
}

// AgentCatalogServiceAPIOption for how the controller is set up.
type AgentCatalogServiceAPIOption func(*AgentCatalogServiceAPIController)

// WithAgentCatalogServiceAPIErrorHandler inject ErrorHandler into controller
func WithAgentCatalogServiceAPIErrorHandler(h ErrorHandler) AgentCatalogServiceAPIOption {
	return func(c *AgentCatalogServiceAPIController) {
		c.errorHandler = h
	}
}

// NewAgentCatalogServiceAPIController creates a default api controller
func NewAgentCatalogServiceAPIController(s AgentCatalogServiceAPIServicer, opts ...AgentCatalogServiceAPIOption) *AgentCatalogServiceAPIController {
	controller := &AgentCatalogServiceAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the AgentCatalogServiceAPIController
func (c *AgentCatalogServiceAPIController) Routes() Routes {
	return Routes{
		"FindAgents": Route{
			"FindAgents",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/agents",
			c.FindAgents,
		},
		"GetAgentFilterOptions": Route{
			"GetAgentFilterOptions",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/agents/filter_options",
			c.GetAgentFilterOptions,
		},
		"GetAgent": Route{
			"GetAgent",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/agents/{agent_id}",
			c.GetAgent,
		},
		"FindAgentSources": Route{
			"FindAgentSources",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/sources",
			c.FindAgentSources,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the AgentCatalogServiceAPIController
func (c *AgentCatalogServiceAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"FindAgents",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/agents",
			c.FindAgents,
		},
		Route{
			"GetAgentFilterOptions",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/agents/filter_options",
			c.GetAgentFilterOptions,
		},
		Route{
			"GetAgent",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/agents/{agent_id}",
			c.GetAgent,
		},
		Route{
			"FindAgentSources",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/sources",
			c.FindAgentSources,
		},
	}
}

// FindAgents - List agents.
func (c *AgentCatalogServiceAPIController) FindAgents(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var nameParam string
	if query.Has("name") {
		param := query.Get("name")

		nameParam = param
	} else {
	}
	var qParam string
	if query.Has("q") {
		param := query.Get("q")

		qParam = param
	} else {
	}
	var sourceLabelParam []string
	if query.Has("sourceLabel") {
		sourceLabelParam = strings.Split(query.Get("sourceLabel"), ",")
	}
	var filterQueryParam string
	if query.Has("filterQuery") {
		param := query.Get("filterQuery")

		filterQueryParam = param
	} else {
	}
	var pageSizeParam string
	if query.Has("pageSize") {
		param := query.Get("pageSize")

		pageSizeParam = param
	} else {
	}
	var orderByParam model.OrderByField
	if query.Has("orderBy") {
		param := model.OrderByField(query.Get("orderBy"))

		orderByParam = param
	} else {
	}
	var sortOrderParam model.SortOrder
	if query.Has("sortOrder") {
		param := model.SortOrder(query.Get("sortOrder"))

		sortOrderParam = param
	} else {
	}
	var nextPageTokenParam string
	if query.Has("nextPageToken") {
		param := query.Get("nextPageToken")

		nextPageTokenParam = param
	} else {
	}
	result, err := c.service.FindAgents(r.Context(), nameParam, qParam, sourceLabelParam, filterQueryParam, pageSizeParam, orderByParam, sortOrderParam, nextPageTokenParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetAgentFilterOptions - Lists fields and values that can be used for filtering.
func (c *AgentCatalogServiceAPIController) GetAgentFilterOptions(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetAgentFilterOptions(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetAgent - Get an `Agent`.
func (c *AgentCatalogServiceAPIController) GetAgent(w http.ResponseWriter, r *http.Request) {
	agentIdParam := chi.URLParam(r, "agent_id")
	if agentIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"agent_id"}, nil)
		return
	}
	result, err := c.service.GetAgent(r.Context(), agentIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// FindAgentSources - List agent catalog sources.
func (c *AgentCatalogServiceAPIController) FindAgentSources(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.FindAgentSources(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
